voxpupuli/puppet-chrony

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/init_spec.rb, templates/chrony.conf.archlinux.erb, templates/chrony.conf.redhat.erb, templates/chrony.keys.archlinux.erb, templates/chrony.keys.redhat.erb
- set default commandkey to 0 (reserved for commands according to chrony docs)
- allow servers to be an array or a hash with options
- configure more than the commandkey in the keys file
=> Make keys more configurable

.travis.yml, Gemfile, spec/classes/init_spec.rb, templates/chrony.conf.archlinux.erb, templates/chrony.conf.redhat.erb
a hash is not guaranteed to be ordered, especially not always in the
same way. So to avoid flipping on the server we should sort the keys
so the output always looks the same.
=> make sure we iterate predictable over the hash

README.md, manifests/init.pp, manifests/params.pp, templates/chrony.conf.archlinux.erb, templates/chrony.conf.debian.erb, templates/chrony.conf.redhat.erb
Configuring this is crucial to enable time stepping e.g. for VMs,
which may be suspended for longer times. Chronys slew mechanism
is in general not appropriate for such huge time jumps.
This is also recommended in the FAQ for chrony:
https://chrony.tuxfamily.org/faq.html#_is_code_chronyd_code_allowed_to_step_the_system_clock
=> Implement "makestep" config parameter.

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, templates/chrony.conf.debian.erb, templates/chrony.conf.redhat.erb
Hello
I'd like to add support for logging options for the [log directive](https://chrony.tuxfamily.org/manual.html#log-directive) for Debian and RedHat
Thanks
John
=> add log_options for logging support

README.md, manifests/init.pp, manifests/params.pp, templates/chrony.conf.debian.erb, templates/chrony.conf.redhat.erb
Making it possible to disable rtcsync via parameter
=> Provide parameter for disabling rtcsync in chrony config file

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.debian.erb, templates/chrony.conf.redhat.erb
This changeset adds a new parameter to `::chrony` so it's possible to change the value of `bindcmdaddress` which is currently hardcoded to localhost4 and localhost6. The default behaviour is kept.
=> Allow configuring bindcmdaddress

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.archlinux.erb, templates/chrony.conf.debian.erb, templates/chrony.conf.redhat.erb
This changeset adds a new parameter `$cmdacl` that allows to set ACLs for monitoring commands using `cmdallow` and `cmddeny`. The previous behaviour on Archlinux is respected by the defaults.
For instance, setting:
```yaml
chrony::cmdacl: ['cmdallow 1.2.3.4', 'cmddeny 1.2.3', 'cmdallow all 1.2']
```
Would result in this snippet being written to the final configuration file:
```
cmdallow 1.2.3.4
cmddeny 1.2.3
cmdallow all 1.2
```
I didn't implement `cmdallow` and `cmddeny` separately because they can be used several times and in the order desired by the caller.
=> Add parameter $cmdacl

metadata.json
Per issue https://github.com/aboe76/puppet-chrony/issues/44 , tested against RHEL8 and revised metadata to reflect this.
Tested ok against RHEL8 and its `chrony-3.3-3.el8.x86_64`.
=> Confirmed RHEL 8 functionality

README.md, manifests/init.pp, spec/classes/chrony_spec.rb
Also document this requirement. Port is at 0 by default
to prevent accidental server mode activation, and if queryhosts
is set the user must also configure port, otherwise this has no effect.
closes #29
=> Fail if queryhosts is set, but port is at default 0.

manifests/init.pp, manifests/install.pp, manifests/params.pp, manifests/service.pp
Why u do this? In each node puppet creates
`Notice: /File[/opt/puppetlabs/puppet/cache/lib/puppet/provider/.gitkeep]/ensure: defined content as '{md5}d41d8cd98f00b204e9800998ecf8427e'
Notice: /File[/opt/puppetlabs/puppet/cache/lib/puppet/type/.gitkeep]/ensure: defined content as '{md5}d41d8cd98f00b204e9800998ecf8427e'
`
=> remove empty dirs and gitkeeps

README.md, manifests/config.pp
This file contains unencrypted shared secrets.  Using `Sensitive` will
stop changes being logged, and exposed in puppetDB etc.
=> Treat keys file content as Sensitive

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.archlinux.erb, templates/chrony.conf.debian.erb, templates/chrony.conf.redhat.erb
Currently, for RedHat and Debian, the module has `stratumweight`
hardcoded to `0`.  Chrony's default has been `0.001` since version 2.0 and
the default configuration file shipped with EL7 doesn't set it to `0`
either. (I suspect a similar situation with modern Debian OSes).
The new parameter defaults to `undef` and leaves out explicitly
configuring `stratumweight` in the configuration file.
This is technically a breaking change as to preserve the
old behaviour, it has to be set to `0`.  I still think this is
preferable to defaulting the parameter to `0` (for OSes other than ArchLinux)
and expecting users to know that `0.001` would be a better choice.
=> Add stratumweight parameter

README.md
There's no ruby code in this module, so this badge isn't applicable.
=> Remove 'Coverage Status' badge

LICENSE, README.md
The full text is needed for GitHub's license detection.
=> Use full Apache 2.0 License text and add badge

REFERENCE.md, manifests/init.pp, manifests/params.pp
By moving the non OS specific defaults back into init.pp, puppet-strings
can now use them in REFERENCE.md
=> Move static defaults out of params.pp

REFERENCE.md, manifests/init.pp, manifests/service.pp, metadata.json, spec/classes/chrony_spec.rb
Also added puppet strings docs for the parameters which previously had
none.
=> Enhance parameter validation with more data types

manifests/config.pp, manifests/init.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.debian.erb, templates/chrony.conf.redhat.erb
This pull request exposes the `leapsectz` option, which when set uses a specified offset from UTC to set `CLOCK_TAI`.
This current revision has tests but could probably benefit from additional work. In addition it looks like the `leapsecmode` option isn't plumbed through on archlinux and I haven't pushed `leapsectz` through either. I'm happy to fix that in another PR or incorporate those fixes here.
=> Add `leapsectz` option config option

REFERENCE.md, manifests/init.pp, spec/classes/chrony_spec.rb
Also remove the requirement for $port to be set if $qeryhost is used. If there is no
'allow' in chrony.conf the server doesn't allow client access, no need to also set port to
0. And if there is 'allow' in chrony.conf the default port to listen on is the expected
123.
From chrony.conf(5)
port port
This option allows the UDP port on which the server understands NTP requests to be
specified. For normal servers this option should not be required (the default is 123,
the standard NTP port).
=> Remove default value of 0 for $port and allow $port to be unset

REFERENCE.md, manifests/init.pp, manifests/params.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.epp
The params added with this PR are:
driftfile, hwtimestamps, rtcsync, and dumpdir. Each with it's separate commit.
=> Add new `driftfile`, `hwtimestamps`, `rtcsync`, and `dumpdir` parameters

manifests/service.pp, templates/chrony.conf.epp
To improve readability.
This is a matter of opinion and taste. Some people prefer to use unless, and some prefer
to use if !. I myself mildly prefer unless, but have no strong feelings. So if there are
anyone that strongly opposes this, it's probably better to just leave it as it is.
=> Change occurrences of 'if !' to 'unless' where possible.

README.md, REFERENCE.md, manifests/init.pp
This uptdates the documentation to match the current code concerning parameter port.
=> Fix documentation about parameter port.

manifests/service.pp, spec/classes/chrony_spec.rb
$service_ensure is required by init.pp to have type Stdlib::Ensure::Service, so there is
no need for this test.
=> Remove unnecessary test on $service_ensure

REFERENCE.md
There has recently been a lot of changes to doc-strings init.pp, and the manually
edited changes to REFERENCE.md doesn't match the doc-strings in init.pp
This change is done by running
puppet strings generate --format markdown manifests/*.pp
=> Regenerate REFERENCE.md

manifests/params.pp, spec/classes/chrony_spec.rb
The service name chrony in Arch Linux is `chronyd`, and the package defines a location under `/var/lib/chrony` for the service to store data instead of `/etc`.
The module is currently broken for Arch Linux out of the box, running the latest version of chrony from the official repos. These changes will allow new instances to work correctly, and shouldn't have much impact on existing installations.
=> Fix Arch Linux configuration

spec/classes/chrony_spec.rb
2.7.9 contains https://github.com/rodjek/rspec-puppet/pull/781 and that
appears to have broken our tests.  Fix was pretty simple, but not sure
the rspec-puppet PR was meant to break existing test suites like this.
=> Fix tests to work with rspec-puppet 2.8.0

.vscode/extensions.json, REFERENCE.md, manifests/init.pp, spec/classes/chrony_spec.rb
The conversion from ERB to EPP in #79 changed the behavior of queryhosts slightly. Before, setting queryhosts to the empty string worked for configuring chrony to allow any query. After, empty string is considered empty, so the "allow" directive would not be rendered.
Enforcing the data type ensures that people upgrading this module who have been using empty string get an error rather than a valid but misconfigured chrony.conf. The replacement for empty string is an array with a single empty string element: ['']
Also, fixing a typo in the tests.
I also removed an obsolete vscode extensions.json (the puppet extension name is obsolete). I have the whole .vscode directory git-ignored, so `bundle exec rake test` aborts when it sees that something ignored exists in the repository. I don't …
=> queryhosts: enforce Array[String] data type

REFERENCE.md, functions/server_array_to_hash.pp, manifests/config.pp, manifests/init.pp, spec/classes/chrony_spec.rb, spec/type_aliases/servers_spec.rb, templates/chrony.conf.epp, types/servers.pp
Before the conversion to epp in
https://github.com/voxpupuli/puppet-chrony/pull/79, an array of
servers/pools would get the `iburst` option set for each server/pool.
This restores the old behaviour and gets rid of the `flatten` magic at
the expense of several extra lines of template.
=> Restore behaviour of `servers` and `pools` parameters

spec/setup_acceptance_node.pp
We are experiencing CI failures on CentOS because the service cannot start because it cannot create it's PID file.
Running the very same test locally works as expected, so the root cause of the different behavior on the CI is unfortunately unknown.  Yet, ensuring the directory for the PID file exist seems to fix the CI issue.
n/a
=> Fix CI on CentOS

manifests/init.pp, spec/classes/chrony_spec.rb
The template uses a conditional statement but it always evaluates to true
and a result users can't disable the usage of local stratum.
We can fix that by adjusting the data type of the local_stratum
parameter to accept the Boolean false value. So, users can set it to
`false` and the template doesn't render the specific block as the
conditional statement evaluates to false.
No issue was opened for this.
=> Allow users to not set local stratum

REFERENCE.md, manifests/config.pp, manifests/init.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.epp
Adds support for managing `maxupdateskew` setting.
The aforementioned setting it wasn't managed and as a result users couldn't set  a value different from the default one.
=> Add support for maxupdateskew

REFERENCE.md, manifests/config.pp, manifests/init.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.epp
Add the `bindaddress` configuration option to chrony.conf.
This will allow users to specify an IP address on an interface on which chronyd should listen.
n/a
=> add bindaddress option

REFERENCE.md, manifests/config.pp, manifests/init.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.epp
Add initstepslew parameter which allows chronyd to make a rapid measurement of the system clock error at boot time, and to correct the system clock by stepping before normal operation begins
Adds new functionality to the module that wasn't available
=> Add initstepslew

manifests/config.pp, manifests/install.pp, manifests/service.pp
Avoid duplicating variables
While here, rely on assert_private() for private classes.
n/a
=> Avoid duplicating variables

manifests/init.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.epp
This PR adds support for the `maxdistance` config option which [`sets the maximum root distance of a source to be acceptable for synchronisation of the clock`](https://chrony.tuxfamily.org/doc/3.4/chrony.conf.html#maxdistance) and may be [required in certain setups (some Windows NTP Servers)](https://chrony.tuxfamily.org/faq.html#_using_a_windows_ntp_server).
I did not find an existing issue for this feature and did not open one as the PR is low-effort and seems straight-forward.
=> Add support for maxdistance

README.md, REFERENCE.md, manifests/init.pp, manifests/params.pp, manifests/service.pp, spec/acceptance/class_spec.rb, spec/classes/chrony_spec.rb
On Redhat and Suse the service `chrony-wait.service` can be enabled and
or started to force the `time-sync.target` to really wait for
synchronisation to occur before proceeding on to other services
that are after `time-sync.target`.
```puppet
class{'chrony':
wait_enable => 'running',
wait_ensure => true,
}
=> Manage chrony-wait.service on RedHat and Suse

.github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, .msync.yml, .puppet-lint.rc, .sync.yml, Dockerfile, Gemfile, REFERENCE.md, data/Archlinux.yaml, functions/server_array_to_hash.pp, manifests/init.pp, spec/acceptance/class_spec.rb, spec/classes/chrony_spec.rb, spec/spec_helper_acceptance.rb
https://archlinux.org/packages/community/x86_64/chrony/ proofes that the
package contains usr/lib/systemd/system/chrony-wait.service.
This PR also contains #140
=> Arch Linux: also manage chrony-wait.service 

manifests/init.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.epp
This patch adds a way to set the chrony options `sched_priority` and `logbanner`.
None
=> Add `sched_priority` and `logbanner` options.

data/RedHat/9.yaml, hiera.yaml, manifests/init.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.epp
Add new defaults for EL9 and a way to explicitly deny query hosts.  Some data constraints and logging options are featured as well.
Replaces: https://github.com/voxpupuli/puppet-chrony/pull/138
Replaces: https://github.com/voxpupuli/puppet-chrony/pull/124
=> Add more config settings and prep EL9 support

REFERENCE.md, manifests/config.pp, manifests/init.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.epp
Previously we always wrote `keyfile` to the chrony configuration file.
This is not always desired. To not cause a breaking change but still
make this configureable, the parameter is now a variant. Besides passing
an absolute path, you can now set it to `''` (empty string). If that's
the case, the keys file won't be managed by Puppet and the option will
be removed from the config file.
=> make config_keys option optional

manifests/init.pp, spec/classes/chrony_spec.rb
The chrony source does not appear to have any restrictions on the range of the logchange value.
See: https://git.tuxfamily.org/chrony/chrony.git/tree/reference.c#n498
=> allow logchange to be a float with an arbitrary range

spec/classes/chrony_spec.rb
Make use of the variables config_file and keys_file to avoid duplicating tests for different OS families.
=> chrony_spec: remove redundant code

spec/classes/chrony_spec.rb
Need to anchor the end of line for these tests to be totally correct. Fixes #163.
=> chrony_spec: fix regexes in "empty allow/deny"

REFERENCE.md, manifests/init.pp, spec/classes/chrony_spec.rb, templates/chrony.conf.epp
Enable setting the optional 'orphan' flag when using local reference mode.
Add a new setting to allow controlling the 'orphan' mode modifier to the 'local' reference mode control. Defaults to the current behavior of not setting orphan mode.
n/a
=> Add 'orphan' mode flag.

manifests/config.pp
Since Puppet 6 already was dropped in 4b4cc870d6c85ea3f16bde8ad0585e4bfad67b90, this Workaround in not needed anymore.
Fixes 8dbe6b4ee897b2225aae9cec4059cee10d763fdf
=> Eliminate Workaround for Sensitive

.github/workflows/ci.yml, .sync.yml
To see if it's indeed no longer a problem, as suggested in https://github.com/voxpupuli/puppet_metadata/pull/103.
=> Drop pidfile_workaround from Beaker testing

REFERENCE.md, manifests/init.pp
=> init: fix `sourcedir` and `confdir` docs

data/Debian.yaml, data/Debian/20.04.yaml, spec/classes/chrony_spec.rb
These settings match the current Debian package default `chrony.conf`:
https://salsa.debian.org/debian/chrony/-/blob/0eae9a1cd2b03c2aaf1af32c7a0840351d9a91e7/debian/chrony.conf
Ubuntu 20.04 has chrony 3.5, which doesn't have the `ntsdumpdir` directive.
=> Add Debian hiera data to match package defaults

data/Debian.yaml, data/Debian/20.04.yaml, spec/classes/chrony_spec.rb
- **Remove Ubuntu 20.04 data**
- **Debian: set config_keys_group to _chrony**
=> Debian: set `config_keys_group` to `_chrony` to match package configuration

README.md
We haven't used Travis-CI in a long time.
=> README: replace Travis status badge with GitHub Actions status
