- .gitignore
- .travis.yml
- Gemfile
- manifests/params.pp
- spec/classes/init_spec.rb
* can't have name as array
* must match error message differently
* enable future parser in travis tests
> fixes for future parser

- templates/chrony.conf.archlinux.erb
Ref
https://chrony.tuxfamily.org/faq.html#_what_happened_to_the_code_commandkey_code_and_code_generatecommandkey_code_directives
> Remove unsupported options

- templates/chrony.conf.redhat.erb
Ref
https://chrony.tuxfamily.org/faq.html#_what_happened_to_the_code_commandkey_code_and_code_generatecommandkey_code_directives
> Removed unsupported options

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- templates/chrony.conf.redhat.erb
Workaround for issue #16 
No docs yet, verified on Fedora 26 only.
> Add refclocks configuration parameter

- .fixtures.yml
- .travis.yml
- Gemfile
- Rakefile
Hi,
This PR propose to improve testing & CI
I also propose to remove old Puppet 3 support in tests with old Ruby version.
Anyway they're deprecated :)
Think Puppet 4 (at least) and 5 should be working with this module!
Regards,
Florian
> improve CI & test with puppet 4/5

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- templates/chrony.conf.archlinux.erb
- templates/chrony.conf.debian.erb
- templates/chrony.conf.redhat.erb
as per https://github.com/aboe76/puppet-chrony/issues/20
Adding : 
- mailonchange
- threshold
- lock_all
Not adding deny for now as i'm not sure if order matter.
Will check this out later!
> [Enhance] adding parameters

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/init_spec.rb
- templates/chrony.conf.archlinux.erb
- templates/chrony.conf.debian.erb
- templates/chrony.conf.redhat.erb
> Add support for pools

- .gitlab-ci.yml
- .sync.yml
- .travis.yml
- Gemfile
- metadata.json
master branch of pdk-templates has a `use_litmus` flag.  Maybe that's all required.
> `pdk update` with `use_litmus`

- README.md
- metadata.json
* Updated metadata.json
* Updated README badges
* Added Copyright and License section with note about Vox Pupuli
maintainership
> Update for Vox Pupuli migration

- manifests/init.pp
- manifests/params.pp
- spec/classes/chrony_spec.rb
- templates/chrony.conf.archlinux.erb
- templates/chrony.conf.debian.erb
- templates/chrony.conf.redhat.erb
Signed-off-by: Florian Pritz <bluewind@xinu.at>
> Support rtconutc option

- examples/init.pp
- manifests/config.pp
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- spec/classes/chrony_spec.rb
puppet-lint flagged these lines
> Resolve puppet-lint notices

- metadata.json
> Drop Eol CentOS 6 support

- README.md
The README notes information about versions under the old namespace.  Cleaned up.
> Drop text pointing to previous repo/version

- metadata.json
Also include:
* https://github.com/voxpupuli/puppet-chrony/pull/117
* https://github.com/voxpupuli/puppet-chrony/pull/118
> Allow stdlib version 7.x

- metadata.json
Also include:
* https://github.com/voxpupuli/puppet-chrony/pull/117
> Add support for Debian 10

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> Bump version to 2.0.0

- README.md
- metadata.json
Declare Ubuntu support and enable testing.
> add Ubuntu support

- spec/acceptance/class_spec.rb
- spec/classes/chrony_spec.rb
Actually run per family acceptance tests on service status.
> Actually test services are running

- metadata.json
Metadata was not updated after last release for some reason.
> Release Candidate 2.0.1-rc0

- .msync.yml
- .puppet-lint.rc
- Gemfile
- Rakefile
- spec/acceptance/class_spec.rb
- spec/classes/chrony_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
- spec/type_aliases/servers_spec.rb
> modulesync 5.1.0

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .msync.yml
- .puppet-lint.rc
- .sync.yml
- Dockerfile
- Gemfile
- REFERENCE.md
- functions/server_array_to_hash.pp
- manifests/init.pp
- spec/spec_helper_acceptance.rb
> modulesync 5.2.0

- manifests/init.pp
- spec/classes/chrony_spec.rb
- templates/chrony.conf.epp
> Add confdir (chrony.cond.d) support

- REFERENCE.md
- manifests/init.pp
- spec/classes/chrony_spec.rb
- templates/chrony.conf.epp
This PR adds support for [ntpsigndsocket](https://chrony.tuxfamily.org/doc/4.2/chrony.conf.html#ntpsigndsocket) option
Fixes #107
> Add support for ntpsigndsocket

- .github/CONTRIBUTING.md
- .msync.yml
- .rubocop.yml
- .rubocop_todo.yml
- Gemfile
> modulesync 5.3.0

- CHANGELOG.md
- REFERENCE.md
- metadata.json
> Prep release 2.4.1

- CHANGELOG.md
- metadata.json
> Release 2.5.0

- .github/CONTRIBUTING.md
- .github/labeler.yml
- .github/release.yml
- .github/workflows/ci.yml
- .github/workflows/labeler.yml
- .github/workflows/prepare_release.yml
- .github/workflows/release.yml
- .msync.yml
- .pmtignore
- .puppet-lint.rc
- Gemfile
- spec/classes/chrony_spec.rb
- spec/spec_helper.rb
> modulesync 9.3.0

- metadata.json
> Add Debian 11 & 12 support

- metadata.json
> Add OracleLinux 8 & 9 support

- metadata.json
> Add Ubuntu 22.04 & 24.04 support
